# Generated by Django 5.0.3 on 2024-03-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_member_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
